export const INCREMENT = 'INCREMENT';
export const INCREMENT_BY_AMOUNT = 'INCREMENT_BY_AMOUNT';
export const DECREMENT = 'DECREMENT';
export const ASYNC_INCREMENT = 'ASYNC_INCREMENT';
export const CHANGE_THEME = 'CHANGE_THEME';
export const DISABLE_BUTTONS = 'DISABLE_BUTTONS';
export const ENABLE_BUTTONS = 'ENABLE_BUTTONS';